package WeeksApp;


/**
* WeeksApp/WeekService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Week.idl
* Saturday, November 19, 2016 3:15:01 PM MSK
*/

public interface WeekService extends WeekServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WeekService
