package WeeksApp;


/**
* WeeksApp/WeekServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Week.idl
* Saturday, November 19, 2016 3:15:01 PM MSK
*/

public interface WeekServiceOperations 
{
  int add (String a, String b);
  void shutdown ();
} // interface WeekServiceOperations
