package DaysApp;


/**
* DaysApp/DayService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Day.idl
* Saturday, November 19, 2016 2:27:58 PM MSK
*/

public interface DayService extends DayServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DayService
