package DaysApp;


/**
* DaysApp/DayServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Day.idl
* Saturday, November 19, 2016 2:27:58 PM MSK
*/

public abstract class DayServicePOA extends org.omg.PortableServer.Servant
 implements DaysApp.DayServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DaysApp/DayService/add
       {
         String a = in.read_string ();
         String b = in.read_string ();
         int $result = (int)0;
         $result = this.add (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // DaysApp/DayService/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DaysApp/DayService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DayService _this() 
  {
    return DayServiceHelper.narrow(
    super._this_object());
  }

  public DayService _this(org.omg.CORBA.ORB orb) 
  {
    return DayServiceHelper.narrow(
    super._this_object(orb));
  }


} // class DayServicePOA
