package DaysApp;


/**
* DaysApp/DayServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Day.idl
* Saturday, November 19, 2016 2:27:58 PM MSK
*/

public interface DayServiceOperations 
{
  int add (String a, String b);
  void shutdown ();
} // interface DayServiceOperations
